In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.dtype

dtype('int64')

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [8]:
x.size

3

In [16]:
y=np.array([[2,3], [1,2]], dtype=np.int32)

In [17]:
y

array([[2, 3],
       [1, 2]], dtype=int32)

In [18]:
y.size

4

In [19]:
y.shape

(2, 2)

In [20]:
y.ndim

2

In [21]:
y.dtype

dtype('int32')

In [22]:
z=np.array([[2,3], [1,2]], dtype=np.float32)

In [23]:
z

array([[ 2.,  3.],
       [ 1.,  2.]], dtype=float32)

In [24]:
z = np.zeros( (5,4) )

In [25]:
z

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
o = np.ones( (4,5) )

In [27]:
o

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [29]:
e = np.eye(4)

In [30]:
e

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [31]:
x

array([1, 2, 3])

In [32]:
x+x

array([2, 4, 6])

In [33]:
x*x

array([1, 4, 9])

In [34]:
y=np.array([[2,3], [1,2]], dtype=np.float32)

In [35]:
y

array([[ 2.,  3.],
       [ 1.,  2.]], dtype=float32)

In [36]:
y.dot(y)

array([[  7.,  12.],
       [  4.,   7.]], dtype=float32)

In [37]:
x.dot(y)

ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

In [38]:
x

array([1, 2, 3])

In [39]:
y

array([[ 2.,  3.],
       [ 1.,  2.]], dtype=float32)

In [40]:
y.T

array([[ 2.,  1.],
       [ 3.,  2.]], dtype=float32)

In [41]:
y.transpose()

array([[ 2.,  1.],
       [ 3.,  2.]], dtype=float32)

In [42]:
y.trace()

4.0

In [43]:
y.diagonal()

array([ 2.,  2.], dtype=float32)

In [47]:
x = np.random.rand(4,4)

In [48]:
x

array([[ 0.68236505,  0.1331919 ,  0.7680889 ,  0.81111053],
       [ 0.50424187,  0.57864866,  0.12593831,  0.8877296 ],
       [ 0.68681099,  0.7141743 ,  0.05992729,  0.16352792],
       [ 0.73310019,  0.24271487,  0.73069784,  0.21107307]])

In [49]:
yt = x.T

In [50]:
yt

array([[ 0.68236505,  0.50424187,  0.68681099,  0.73310019],
       [ 0.1331919 ,  0.57864866,  0.7141743 ,  0.24271487],
       [ 0.7680889 ,  0.12593831,  0.05992729,  0.73069784],
       [ 0.81111053,  0.8877296 ,  0.16352792,  0.21107307]])

In [51]:
yt[2,2] = 14.0

In [52]:
yt

array([[  0.68236505,   0.50424187,   0.68681099,   0.73310019],
       [  0.1331919 ,   0.57864866,   0.7141743 ,   0.24271487],
       [  0.7680889 ,   0.12593831,  14.        ,   0.73069784],
       [  0.81111053,   0.8877296 ,   0.16352792,   0.21107307]])

In [53]:
x

array([[  0.68236505,   0.1331919 ,   0.7680889 ,   0.81111053],
       [  0.50424187,   0.57864866,   0.12593831,   0.8877296 ],
       [  0.68681099,   0.7141743 ,  14.        ,   0.16352792],
       [  0.73310019,   0.24271487,   0.73069784,   0.21107307]])

In [54]:
yt[0,3] = -42.0

In [55]:
yt

array([[  0.68236505,   0.50424187,   0.68681099, -42.        ],
       [  0.1331919 ,   0.57864866,   0.7141743 ,   0.24271487],
       [  0.7680889 ,   0.12593831,  14.        ,   0.73069784],
       [  0.81111053,   0.8877296 ,   0.16352792,   0.21107307]])

In [56]:
x

array([[  0.68236505,   0.1331919 ,   0.7680889 ,   0.81111053],
       [  0.50424187,   0.57864866,   0.12593831,   0.8877296 ],
       [  0.68681099,   0.7141743 ,  14.        ,   0.16352792],
       [-42.        ,   0.24271487,   0.73069784,   0.21107307]])

In [57]:
xcopy = x.copy()

In [58]:
x

array([[  0.68236505,   0.1331919 ,   0.7680889 ,   0.81111053],
       [  0.50424187,   0.57864866,   0.12593831,   0.8877296 ],
       [  0.68681099,   0.7141743 ,  14.        ,   0.16352792],
       [-42.        ,   0.24271487,   0.73069784,   0.21107307]])

In [59]:
x.shape

(4, 4)

In [63]:
x.reshape((1,16))

array([[  0.68236505,   0.1331919 ,   0.7680889 ,   0.81111053,
          0.50424187,   0.57864866,   0.12593831,   0.8877296 ,
          0.68681099,   0.7141743 ,  14.        ,   0.16352792,
        -42.        ,   0.24271487,   0.73069784,   0.21107307]])

In [65]:
x.ravel('F')

array([  0.68236505,   0.50424187,   0.68681099, -42.        ,
         0.1331919 ,   0.57864866,   0.7141743 ,   0.24271487,
         0.7680889 ,   0.12593831,  14.        ,   0.73069784,
         0.81111053,   0.8877296 ,   0.16352792,   0.21107307])

In [67]:
np.arange(0,3,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7])

In [68]:
np.linspace(0,3,11)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7,  3. ])

### 1d and 2d finite difference indexing examples

In [69]:
def laplace1d(x):
    numelem = x.size
    outvec = x.copy()
    for i in range(1,numelem-1):
        newval = x[i+1] - 2*x[i] + x[i-1]
        outvec[i] = newval
    return outvec

In [70]:
def laplace2d(x):
    sh = x.shape
    outvec = x.copy()
    for i in range(1,sh[0]-1):
        for j in range(1,sh[1]-1):
            newval = x[i+1,j] + x[i-1,j] + x[i,j+1] + x[i,j-1] - 4*u[i,j]
            outvec[i,j] = newval
    return outvec